import type {
  AppState,
  Budget,
  CategorizationRule,
  Category,
  FinancialAccount,
  FinancialGoal,
  Household,
  HouseholdMember,
  ImportBatch,
  Merchant,
  RecurringRule,
  Tag,
  Transaction,
} from './model'

const now = new Date()
const isoToday = now.toISOString().slice(0, 10)
const createdAt = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 0, 0).toISOString()
const nextWeekdayIso = (weekday: number) => {
  const date = new Date(now)
  const daysAhead = (weekday - date.getDay() + 7) % 7
  date.setDate(date.getDate() + daysAhead)
  return date.toISOString().slice(0, 10)
}

const createHousehold = (): Household => ({
  id: crypto.randomUUID(),
  name: 'Our Home',
  currency: 'USD',
  locale: 'en-US',
  financialMonthStartDay: 1,
  weekStartDay: 1,
  createdAt,
})

const members = (householdId: string): HouseholdMember[] => [
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'You',
    role: 'Household member',
    color: '#2F7D5B',
    active: true,
  },
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'Partner',
    role: 'Household member',
    color: '#4A6FA5',
    active: true,
  },
]

const categories = (householdId: string): Category[] => [
  ['Housing', 'Essentials', '#8B6F9C', 'Home'],
  ['Groceries', 'Essentials', '#2F7D5B', 'ShoppingCart'],
  ['Dining', 'Lifestyle', '#D97757', 'UtensilsCrossed'],
  ['Transport', 'Essentials', '#4A6FA5', 'CarFront'],
  ['Fuel', 'Essentials', '#C8795C', 'Fuel'],
  ['Health', 'Essentials', '#6BA368', 'HeartPulse'],
  ['Insurance', 'Protection', '#5E84B5', 'Shield'],
  ['Education', 'Personal', '#8B6F9C', 'GraduationCap'],
  ['Leisure', 'Lifestyle', '#C57891', 'Ticket'],
  ['Subscriptions', 'Fixed', '#A26078', 'Repeat'],
  ['Phone & Internet', 'Fixed', '#607FAE', 'Wifi'],
  ['Electricity', 'Fixed', '#D97757', 'Zap'],
  ['Water', 'Fixed', '#68A4B8', 'Droplets'],
  ['Taxes', 'Fixed', '#B9874D', 'Receipt'],
  ['Clothing', 'Variable', '#5A9B8E', 'Shirt'],
  ['Gifts', 'Variable', '#A875A2', 'Gift'],
  ['Travel', 'Goals', '#4A86A5', 'Plane'],
  ['Pets', 'Family', '#83A85B', 'PawPrint'],
  ['Debt', 'Finance', '#D97757', 'HandCoins'],
  ['Investments', 'Finance', '#2F7D5B', 'ChartLine'],
  ['Salary', 'Income', '#2F7D5B', 'BriefcaseBusiness'],
  ['Extra income', 'Income', '#6BA368', 'BadgePlus'],
  ['Refunds', 'Income', '#5A9B8E', 'ReceiptText'],
  ['Transfers', 'Transfers', '#6B7373', 'ArrowLeftRight'],
  ['Other', 'Other', '#7D8585', 'CircleEllipsis'],
].map(([name, group, color, icon], index) => ({
  id: crypto.randomUUID(),
  householdId,
  name,
  group,
  order: index,
  archived: false,
  color,
  icon,
}))

const accountIds: Record<string, string> = {}

const accounts = (householdId: string): FinancialAccount[] => {
  const list = [
    {
      name: 'Everyday account',
      institution: 'AIB',
      type: 'current' as const,
      openingBalanceCents: 241_200,
      holder: 'Joint',
      accentColor: '#0f766e',
      archived: false,
      notes: 'Main household account.',
    },
    {
      name: 'Bills account',
      institution: 'AIB',
      type: 'joint' as const,
      openingBalanceCents: 184_500,
      holder: 'Household',
      accentColor: '#7c3aed',
      archived: false,
      notes: 'Shared bills and household expenses.',
    },
    {
      name: 'Credit card',
      institution: 'Revolut',
      type: 'credit-card' as const,
      openingBalanceCents: -52_300,
      holder: 'You',
      accentColor: '#dc2626',
      archived: false,
      notes: 'Paid in full each month.',
    },
    {
      name: 'Savings',
      institution: 'AIB',
      type: 'savings' as const,
      openingBalanceCents: 1_284_000,
      holder: 'Household',
      accentColor: '#16a34a',
      archived: false,
      notes: 'Emergency fund.',
    },
  ]

  return list.map((item) => {
    const id = crypto.randomUUID()
    accountIds[item.name] = id

    return {
      id,
      householdId,
      currency: 'USD',
      currentBalanceCents: item.openingBalanceCents,
      ...item,
    }
  })
}

const merchants = (householdId: string): Merchant[] => [
  'Tesco',
  'Netflix',
  'AIB',
  'Dublin Bus',
  'Energia Solar',
  'Tesco Express',
  'Pharmacy Plus',
  'Vodafone',
].map((name) => ({
  id: crypto.randomUUID(),
  householdId,
  name,
  normalizedName: name.toUpperCase(),
}))

const tags = (householdId: string): Tag[] => [
  { id: crypto.randomUUID(), householdId, name: 'fixed', color: '#4A6FA5' },
  { id: crypto.randomUUID(), householdId, name: 'urgent', color: '#D97757' },
  { id: crypto.randomUUID(), householdId, name: 'recurring', color: '#2F7D5B' },
]

const categoryByName = (items: Category[], name: string) =>
  items.find((item) => item.name === name)?.id ?? items[0].id

const transactions = (householdId: string, categoryList: Category[]): Transaction[] => {
  const byName = {
    salary: categoryByName(categoryList, 'Salary'),
    supermarket: categoryByName(categoryList, 'Groceries'),
    rent: categoryByName(categoryList, 'Housing'),
    energy: categoryByName(categoryList, 'Electricity'),
    internet: categoryByName(categoryList, 'Phone & Internet'),
    transport: categoryByName(categoryList, 'Transport'),
    subscriptions: categoryByName(categoryList, 'Subscriptions'),
    dining: categoryByName(categoryList, 'Dining'),
    savings: categoryByName(categoryList, 'Investments'),
    transfer: categoryByName(categoryList, 'Transfers'),
    other: categoryByName(categoryList, 'Other'),
  }

  const account = (key: keyof typeof accountIds) => accountIds[key]

  return [
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'My salary',
      description: 'Weekly salary',
      amountCents: 180_000,
      type: 'income',
      categoryId: byName.salary,
      accountId: account('Everyday account'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'received',
      personId: 'You',
      payee: 'Employer',
      paymentMethod: 'Bank transfer',
      tags: ['fixed'],
      notes: '',
      source: 'manual',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Rent',
      description: 'Monthly rent',
      amountCents: 135_000,
      type: 'expense',
      categoryId: byName.rent,
      accountId: account('Everyday account'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'paid',
      personId: 'Household',
      payee: 'Landlord',
      paymentMethod: 'Direct debit',
      tags: ['fixed'],
      notes: 'Main fixed household expense.',
      source: 'manual',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Tesco weekly shop',
      description: 'Weekly groceries',
      amountCents: 14_500,
      type: 'expense',
      categoryId: byName.supermarket,
      accountId: account('Everyday account'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'paid',
      personId: 'Partner',
      payee: 'Tesco',
      paymentMethod: 'Card',
      tags: ['recurring'],
      notes: '',
      source: 'imported',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Netflix',
      description: 'Monthly subscription',
      amountCents: 1_499,
      type: 'expense',
      categoryId: byName.subscriptions,
      accountId: account('Credit card'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'paid',
      personId: 'You',
      payee: 'Netflix',
      paymentMethod: 'Card',
      tags: ['recurring'],
      notes: '',
      source: 'imported',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Fuel',
      description: 'Car fuel',
      amountCents: 6_500,
      type: 'expense',
      categoryId: byName.transport,
      accountId: account('Credit card'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'paid',
      personId: 'Partner',
      payee: 'BP',
      paymentMethod: 'Card',
      tags: [],
      notes: '',
      source: 'manual',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Savings contribution',
      description: 'Monthly savings transfer',
      amountCents: 250_000,
      type: 'transfer',
      categoryId: byName.transfer,
      accountId: account('Everyday account'),
      counterpartyAccountId: account('Savings'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'paid',
      personId: 'Household',
      payee: 'Savings',
      paymentMethod: 'Bank transfer',
      tags: ['recurring'],
      notes: '',
      source: 'manual',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Electricity',
      description: 'Electricity bill',
      amountCents: 12_800,
      type: 'expense',
      categoryId: byName.energy,
      accountId: account('Everyday account'),
      transactionDate: isoToday,
      dueDate: isoToday,
      status: 'pending',
      personId: 'Household',
      payee: 'Electric Ireland',
      paymentMethod: 'Direct debit',
      tags: ['fixed'],
      notes: '',
      source: 'manual',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: crypto.randomUUID(),
      householdId,
      title: 'Extra income',
      description: 'Freelance work',
      amountCents: 42_000,
      type: 'income',
      categoryId: byName.salary,
      accountId: account('Everyday account'),
      transactionDate: isoToday,
      dueDate: isoToday,
      paidDate: isoToday,
      status: 'received',
      personId: 'You',
      payee: 'Client',
      paymentMethod: 'Transfer',
      tags: [],
      notes: '',
      source: 'manual',
      splits: [],
      createdAt,
      updatedAt: createdAt,
    },
  ]
}

const recurringRules = (householdId: string, categoryList: Category[]): RecurringRule[] => [
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'My salary',
    amountCents: 180_000,
    frequency: 'weekly',
    interval: 1,
    nextDueDate: nextWeekdayIso(5),
    accountId: accountIds['Everyday account'],
    categoryId: categoryByName(categoryList, 'Salary'),
    personId: 'You',
    generateAutomatically: true,
    reminder: true,
    active: true,
  },
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'Partner salary',
    amountCents: 150_000,
    frequency: 'weekly',
    interval: 1,
    nextDueDate: nextWeekdayIso(4),
    accountId: accountIds['Everyday account'],
    categoryId: categoryByName(categoryList, 'Salary'),
    personId: 'Partner',
    generateAutomatically: true,
    reminder: true,
    active: true,
  },
  ...[
    ['Rent', 135_000, 'Housing'],
    ['Groceries', 14_500, 'Groceries'],
    ['Internet', 6_500, 'Phone & Internet'],
    ['Electricity', 12_800, 'Electricity'],
    ['Gas', 6_000, 'Electricity'],
    ['Car insurance', 9_800, 'Insurance'],
    ['Streaming', 1_499, 'Subscriptions'],
    ['Phone', 4_500, 'Phone & Internet'],
  ].map(([name, amountCents, categoryName], index) => ({
    id: crypto.randomUUID(),
    householdId,
    name: String(name),
    amountCents: Number(amountCents),
    frequency: index === 1 ? 'weekly' as const : 'monthly' as const,
    interval: 1,
    nextDueDate: isoToday,
    accountId: accountIds[index === 6 ? 'Credit card' : 'Everyday account'],
    categoryId: categoryByName(categoryList, String(categoryName)),
    personId: 'Household',
    generateAutomatically: true,
    reminder: true,
    active: true,
  })),
]

const budgets = (householdId: string, categoryList: Category[]): Budget[] => [
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'Monthly household budget',
    scope: 'general',
    period: 'monthly',
    limitCents: 3_200_000,
    flexible: false,
    rollover: true,
    archived: false,
  },
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'Groceries',
    scope: 'category',
    period: 'monthly',
    limitCents: 450_000,
    categoryId: categoryByName(categoryList, 'Groceries'),
    flexible: true,
    rollover: false,
    archived: false,
  },
]

const goals = (householdId: string): FinancialGoal[] => [
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'Emergency fund',
    targetCents: 500_000,
    currentCents: 120_000,
    targetDate: new Date(now.getFullYear() + 1, now.getMonth(), now.getDate()).toISOString().slice(0, 10),
    monthlyContributionCents: 40_000,
    accountId: accountIds['Savings'],
    priority: 1,
    notes: 'Our most important household goal.',
    archived: false,
  },
  {
    id: crypto.randomUUID(),
    householdId,
    name: 'Vacation',
    targetCents: 200_000,
    currentCents: 40_000,
    targetDate: new Date(now.getFullYear() + 1, now.getMonth() + 5, now.getDate()).toISOString().slice(0, 10),
    monthlyContributionCents: 20_000,
    accountId: accountIds['Savings'],
    priority: 2,
    notes: 'A relaxed family trip.',
    archived: false,
  },
]

const categorizationRules = (householdId: string, categoryList: Category[]): CategorizationRule[] => [
  {
    id: crypto.randomUUID(),
    householdId,
    priority: 100,
    field: 'description',
    operator: 'contains',
    pattern: 'TESCO',
    categoryId: categoryByName(categoryList, 'Groceries'),
    active: true,
    applyToExisting: true,
    notes: 'Tesco and Tesco Express go to groceries.',
  },
  {
    id: crypto.randomUUID(),
    householdId,
    priority: 90,
    field: 'description',
    operator: 'contains',
    pattern: 'NETFLIX',
    categoryId: categoryByName(categoryList, 'Subscriptions'),
    active: true,
    applyToExisting: true,
    notes: 'Monthly streaming.',
  },
  {
    id: crypto.randomUUID(),
    householdId,
    priority: 80,
    field: 'description',
    operator: 'contains',
    pattern: 'AIB TRANSFER',
    categoryId: categoryByName(categoryList, 'Transfers'),
    active: true,
    applyToExisting: true,
    notes: 'Internal bank transfer.',
  },
]

export function createDemoState(): AppState {
  const household = createHousehold()
  const categoryList = categories(household.id)
  const accountList = accounts(household.id)

  return {
    schemaVersion: 1,
    initializedAt: createdAt,
    onboardingCompleted: true,
    demoEnabled: true,
    household,
    members: members(household.id),
    accounts: accountList,
    categories: categoryList,
    merchants: merchants(household.id),
    transactions: transactions(household.id, categoryList),
    recurringRules: recurringRules(household.id, categoryList),
    budgets: budgets(household.id, categoryList),
    goals: goals(household.id),
    tags: tags(household.id),
    categorizationRules: categorizationRules(household.id, categoryList),
    imports: [
      {
        id: crypto.randomUUID(),
        householdId: household.id,
        sourceName: 'AIB CSV',
        sourceType: 'csv',
        importedAt: createdAt,
        rowCount: 3,
        duplicateCount: 1,
        status: 'confirmed',
        notes: 'Initial sample import.',
      } satisfies ImportBatch,
    ],
    importRows: [],
    attachments: [],
    backups: [],
    auditEvents: [],
    forecastSnapshots: [],
    settings: {
      theme: 'light',
      privacyMode: false,
      hideSensitiveValues: false,
      locale: 'en-US',
      currency: 'USD',
      weekStartDay: 1,
      financialMonthStartDay: 1,
      pinEnabled: false,
      appLocked: false,
      lastBackupAt: undefined,
      backupDirectory: undefined,
    },
  }
}

export function createBlankState(): AppState {
  const household = {
    id: crypto.randomUUID(),
    name: 'HomeCoin Household',
    currency: 'USD',
    locale: 'en-US',
    financialMonthStartDay: 1,
    weekStartDay: 1,
    createdAt,
  }

  return {
    schemaVersion: 1,
    initializedAt: createdAt,
    onboardingCompleted: false,
    demoEnabled: false,
    household,
    members: [],
    accounts: [],
    categories: categories(household.id),
    merchants: [],
    transactions: [],
    recurringRules: [],
    budgets: [],
    goals: [],
    tags: [],
    categorizationRules: [],
    imports: [],
    importRows: [],
    attachments: [],
    backups: [],
    auditEvents: [],
    forecastSnapshots: [],
    settings: {
      theme: 'light',
      privacyMode: false,
      hideSensitiveValues: false,
      locale: 'en-US',
      currency: 'USD',
      weekStartDay: 1,
      financialMonthStartDay: 1,
      pinEnabled: false,
      appLocked: false,
    },
  }
}
